eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
spring:
  application:
    name: service-feign-order
#开启fegin的断路器
fegin:
  hystrix:
    enabled: true