eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8090
spring:
  application:
    name: service-feign-order
#表示开启fegin的断路器功能
feign:
  hystrix:
    enabled: true