eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
server:
  port: 8080
spring:
  application:
    name: eureka-customer