eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    #http://localhost:8769/api-member/getMember会路由到member服务
    api-a:
      path: /api-member/**
      serviceId: service-feign-member
    api-b:
      path: /api-order/**
      serviceId: service-feign-order